- src/triple.rs
We currently have this logic in Cranelift, but it could be usable in other things too.
> Add the ability to return the default calling convention for a triple.

- src/targets.rs
`armv7ve` is `armv7` with virtualization extensions
See GCC mailing list for initial patches:
https://gcc.gnu.org/ml/gcc-patches/2013-12/msg01783.html
> Add support for `armv7ve` architecture

- src/targets.rs
- src/triple.rs
This change moves Arm architectures to a separate enum, `ArmArchitecture`. Overall, I think this is heading in a useful direction, but I'm not really thrilled with the implementation here.
1. Should `Aarch64` live under `ArmArchitecture`?
2. What is the source of truth? Eg: LLVM aliases `arm64` -> `aarch64`. Should we copy this behavior?
3. Is FPU information useful?
4. `is_thumb` returns a bool with the given arch triple's thumb-ness. This doesn't seem terribly useful - I think it would be more helpful to have a `supports_thumb` fn to return actual ISA support. Thoughts?
Arm processor list and FPU list copied from:
https://github.com/gcc-mirror/gcc/blob/master/gcc/config/arm/arm-cpus.in#L261
See also:
https://github.com/llvm-mirror/llvm/blob/master/lib/Target/ARM/ARM.td …
> Add broad Arm architecture support

- build.rs
- examples/host.rs
Allows using `host` for initializing `const` and `static` values.
Adds an example of using host in a const context.
Affects the following enums and structs:
- `Architecture`
- `Vendor`
- `OperatingSystem`
- `Environment`
- `BinaryFormat`
- `Triple`
Addresses https://github.com/CraneStation/target-lexicon/issues/18
> Make `host` a const function

- src/targets.rs
> Ensure that the binary format for thumbv7em-none-eabihf is ELF.

- Cargo.toml
- build.rs
- src/lib.rs
- src/parse_error.rs
- src/targets.rs
- src/triple.rs
liballoc is now stable as of Rust 1.36, so use it to simplify no_std
support. target-lexicon can now just support no_std by default, without
using cargo features.
> Update no_std support.

- Cargo.toml
- src/targets.rs
- src/triple.rs
This updates to the list of targets in the lastest Rust builds, and bumps the version number for publishing.
> Update target list and bump to 0.9.0.

- build.rs
- src/lib.rs
- src/targets.rs
- src/triple.rs
Add support for custom vendors, as in "x86_64-gentoo-linux-musl".
Fixes #33.
> Support custom vendor strings.

- src/targets.rs
This will let us add new targets without semver-incompatible API changes.
Fixes #37.
> Mark target enums `#[non_exhaustive]`.

- src/targets.rs
This makes them easier to work with for users that want to handle all
riscv32 or riscv64 targets in the same way. And the new enums are
non-exhaustive, so we can add new subtarget variants without breaking
compatibility.
> Move the Riscv32, Riscv64, and X86_32 targets into subtarget enums.

- src/targets.rs
wasm64 is an early prototyping phase, but the name of the target is
sufficiently stable that we can add it here.
See also https://github.com/WebAssembly/design/issues/1325.
> Add a wasm64 target.

- src/triple.rs
See https://github.com/rust-lang/rust/blob/9ebf47851a357faa4cd97f4b1dc7835f6376e639/src/librustc_target/spec/hermit_base.rs, as well as https://hermitcore.org/getting-started/#as-multi-kernel-within-a-virtual-machine which seems to indicate ABI-compatibility with Linux (?)
> Mark hermit as unix-like

- build.rs
- src/data_model.rs
- src/lib.rs
- src/targets.rs
- src/triple.rs
Closes #47 
- ~~Rename `PointerWidth` to `Size` and use it for other types as well~~
- Add new `Size` enum
- Add `CDataModel` and `data_model()` function to `impl Triple`
My main question is how to tell what data model belongs to which target. I have some very broad heuristics but there's too many possible triples to match them all exhaustively (over 200000!)
> [WIP] Start on adding C type sizes

- src/targets.rs
This is similar to how ARM, Risc-v, etc. are factored out, and will make
it easier to add new architecture variants without breaking semver
compatibility.
> Factor out Mips architectures into architecture-specific enums.

- src/lib.rs
This isn't much code, and is convenient for users that were previously using the `Default` implementation on `Triple`.
> Add a utility to implement Default using Triple::unknown() too.

- .travis.yml
- Cargo.toml
- build.rs
- src/data_model.rs
- src/lib.rs
- src/targets.rs
- src/triple.rs
- Change `Self::Variant` to `T::Variant`
- Use `extern crate alloc;` only with `no_std`. `no_std` and 1.34 are not supported
- Detect whether using rust 1.40 or greater in `build.rs`. If so, use `#[non_exhaustive]` on enums.
- Add 1.34.0 to CI
Closes https://github.com/bytecodealliance/target-lexicon/issues/58.
> Add backwards compatibility with 1.34

- build.rs
It turns out it didn't actually work, the logic in `using_1_40` was wrong. I didn't notice because I only tested with 1.40 after addressing review comments.
I guess that means that the 1.34 check in CI didn't run? Is there a way to set that up? Otherwise I'm worried people will accidentally change the minimum version without meaning to.
> Fix 1.34 support

- src/targets.rs
- src/triple.rs
There were several targets missing support from the available 1.47.0 target list, this PR adds them all.
- `avr` arch - `"avr-unknown-unknown"`
- `thumbv4t` arch - `"thumbv4t-none-eabi"`
- `tvos` operating system - `"aarch64-apple-tvos"` `"x86_64-apple-tvos"`
> Add support for missing 1.47.0 targets

- build.rs
When the vendor is not recognized, the build script generates `Vendor::CustomVendor::Static("foo")`. This isn't valid.
This PR fixes it to `Vendor::Custom(CustomVendor::Static("foo"))`, as I suppose it's intended.
> Fix build when vendor is unknown

- src/triple.rs
Apple Aarch64 platforms use their own variant of the common Aarch64
calling convention. Add a `CallingConvention` value for it.
Fixes #69.
> Add an `AppleAarch64` calling convention.

- src/triple.rs
This will make adding new calling conventions semver-compatible.
> Mark the `CallingConvention` enum as `non_exhaustive`.

- src/targets.rs
These targets are for big-endian and little-endian versions of the Linux
bpf subsystem, respectively. They were added in Rust 1.54.
> Add bpfeb and bpfel targets

- src/targets.rs
> Add support for riscv32im architecture

- src/targets.rs
- src/triple.rs
This adds support for the `clever` architecture, including version specifiers. 
Clever-ISA is defined by <https://github.com/Clever-ISA/Clever-ISA> and the format of targets is defined by the toolchain recommendations technical document (specs/toolchain.md or referred to as D-toolchain).  This PR supports both the "bare" clever name specifier, as well as ones with a version suffix. The targets are also supported by the similar target parsing library, [target-tuples](https://crates.io/crates/target-tuples). 
The support is being added so I can add the architecture to a fork cranelift code generator, for the purposes of using it via rustc_codegen_cranelift. Proposing to upstream the modification to cranelift is a possibility depending on how well it goes.
> Add Clever architecture

- src/lib.rs
When using either `DefaultToHost` or `DefaultToUnknown` structs (which are named tuples with `Default` implementations), the developer loses the benefits of being able to use them in `Clone`, `Debug`, `PartialEq`, `Eq`, and `Hash` contexts.
This commit adds the `#[derive]` macros to these structs to retain these traits from `Triple`.
> DefaultTo* structs derive Clone, Debug, etc.

- src/targets.rs
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html
> Add support for loongarch64 architecture

- src/triple.rs
This way the caller doesn't need to import `FromStr`.
> Use fully-qualified syntax in `triple!` for calling `from_str`

- src/targets.rs
https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64h-apple-darwin.html
> Add support for target `x86_64h-apple-darwin`

- Cargo.toml
- src/targets.rs
This is a very initial take on this if only to be able to specify `zkasm-unknown-unknown` target in tooling that uses `target-lexicon`. Some of the details are not exactly 100% correct in the current state of the machine (e.g. pointer width is 256 bits), but this will potentially change soon…
> Add a zkASM architecture

- src/targets.rs
- src/triple.rs
x32 and ilp32 are ABI variants on x86_64 and aarch64 platforms where pointers have 32-bit, even though the CPU architectures are 64-bit. Fix target-lexicon to correctly report the pointer width for these.
Fixes #97.
> Fix the `Target::pointer_width` value on x32 and ilp32 targets.

- src/targets.rs
- src/triple.rs
* `wasm32-wasip1`
* `wasm32-wasip2`
* `wasm32-wasip1-threads`
> Add support for some new WASI targets:

- .github/actions/install-rust/main.js
- src/lib.rs
Ignoring unexpected_cfgs warnings, now that Rust warns about them.
> Ignore unexpected_cfgs warnings

- src/targets.rs
- src/triple.rs
This updates Fuchsia targets to print the `unknown` vendor, and adds several more new targets.
> Update to the more upstream Rust targets.

- src/targets.rs
- src/triple.rs
Following the [logic in LLVM], make the binary format for most targets be ELF instead of Unknown. To preserve round-tripping for Rust target names, this requires some special-casing in the formatting code, but this isn't new; a lot of targets require special cases to round-trip properly.
[logic in LLVM]: https://github.com/llvm/llvm-project/blob/d3e7c4ce7a3d7f08cea02cba8f34c590a349688b/llvm/lib/TargetParser/Triple.cpp#L877
> Fix the default binary format for most architectures to be ELF.

- src/targets.rs
"pbc" = Pulley Bytecode. The 32 and 64 refer to the pointer size.
> Add `pbc32` and `pbc64` architectures for Pulley

- src/host.rs
- src/targets.rs
- src/triple.rs
Also allow it to be optional, or partially specified.
This is a breaking change.
I've chosen to keep `Darwin` as a separate OS, since it seems like in https://github.com/bytecodealliance/target-lexicon/issues/111#issuecomment-2388418787 that this crate wants to focus on LLVM target triples.
Another solution would've been to merge it into `OperatingSystem::MacOSX`, and just ignore that `"darwin"` doesn't technically mean that (though it is likely to in practice). If we chose this solution (which would be focusing more on `rustc` targets), I would probably not want to parse the version at all, and just ignore it instead.
> Parse the deployment target on all Apple target triples

- Cargo.toml
- README.md
- src/lib.rs
- src/triple.rs
Fixes https://github.com/bytecodealliance/target-lexicon/issues/111.
> Make it clear in docs that we parse LLVM triples

- src/targets.rs
In the development of Pulley for Wasmtime we've realized that we're going to need big-endian variants of Pulley in addition to little-endian, so add that here.
> Add big-endian Pulley targets

- src/lib.rs
Otherwise you can't pattern match it on `OperatingSystem::Darwin()` etc.
> feat: make `DeploymentTarget` public
